{{- if .Values.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metal-load-balancer-controller-manager-leader-election
  namespace: kube-system
  labels:
    app.kubernetes.io/name: metal-load-balancer-controller-manager
    app.kubernetes.io/instance: metal-load-balancer-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metal-load-balancer-controller-manager-leader-election
subjects:
  - kind: ServiceAccount
    name: metal-load-balancer-controller-manager
    namespace: kube-system
{{- end }}
